name: CI/CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_REPO: polaris-secuone-dashboard
  IMAGE_LATEST: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_REPO }}:latest
  IMAGE_SHA:    ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_REPO }}:sha-${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Test & Build (Maven)
        run: ./mvnw -q -DskipTests package
      - name: Login GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build & Push image
        run: |
          docker build -t "$IMAGE_LATEST" -t "$IMAGE_SHA" .
          docker push "$IMAGE_LATEST"
          docker push "$IMAGE_SHA"

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Login GHCR (read)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Pull & Up
        run: |
          cd /home/tomcat/secuone
          docker pull "$IMAGE_LATEST"
          docker compose up -d
          docker image prune -f
