name: CI/CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# 내장 토큰 권한 설정: 패키지 쓰기(푸시) 허용
permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_REPO: polaris-secuone-dashboard
  IMAGE_LATEST: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_REPO }}:latest
  IMAGE_SHA:    ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_REPO }}:sha-${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # Maven 빌드
      - name: Test & Build (Maven)
        run: ./mvnw -q -DskipTests package

      # GHCR 로그인: 내장 GITHUB_TOKEN 사용 (시크릿 추가 불필요)
      - name: Login GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build & Push
        run: |
          docker build -t "$IMAGE_LATEST" -t "$IMAGE_SHA" .
          docker push "$IMAGE_LATEST"
          docker push "$IMAGE_SHA"

  deploy:
    needs: build-and-push
    # 서버에 설치한 self-hosted 러너 라벨과 일치해야 함
    runs-on: [self-hosted, linux, x64, secuone]
    steps:
      - name: Login GHCR (read)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Pull & up
        run: |
          cd /home/tomcat/secuone
          docker pull "$IMAGE_LATEST"
          docker compose up -d
          docker image prune -f
