name: Runner smoke
on:
  push:
    paths:
      - .github/workflows/runner-smoke.yml

jobs:
  smoke:
    runs-on: self-hosted
    steps:
      - name: Print env
        run: |
          whoami
          id
      - name: Docker check
        run: |
          docker --version
          docker ps
          docker compose version
